/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScaleComplementiRouteImport } from './routes/scale-complementi'
import { Route as RivestimentiRouteImport } from './routes/rivestimenti'
import { Route as PianiCucinaBagnoRouteImport } from './routes/piani-cucina-bagno'
import { Route as ArteFunerariaRouteImport } from './routes/arte-funeraria'
import { Route as IndexRouteImport } from './routes/index'

const ScaleComplementiRoute = ScaleComplementiRouteImport.update({
  id: '/scale-complementi',
  path: '/scale-complementi',
  getParentRoute: () => rootRouteImport,
} as any)
const RivestimentiRoute = RivestimentiRouteImport.update({
  id: '/rivestimenti',
  path: '/rivestimenti',
  getParentRoute: () => rootRouteImport,
} as any)
const PianiCucinaBagnoRoute = PianiCucinaBagnoRouteImport.update({
  id: '/piani-cucina-bagno',
  path: '/piani-cucina-bagno',
  getParentRoute: () => rootRouteImport,
} as any)
const ArteFunerariaRoute = ArteFunerariaRouteImport.update({
  id: '/arte-funeraria',
  path: '/arte-funeraria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arte-funeraria': typeof ArteFunerariaRoute
  '/piani-cucina-bagno': typeof PianiCucinaBagnoRoute
  '/rivestimenti': typeof RivestimentiRoute
  '/scale-complementi': typeof ScaleComplementiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arte-funeraria': typeof ArteFunerariaRoute
  '/piani-cucina-bagno': typeof PianiCucinaBagnoRoute
  '/rivestimenti': typeof RivestimentiRoute
  '/scale-complementi': typeof ScaleComplementiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arte-funeraria': typeof ArteFunerariaRoute
  '/piani-cucina-bagno': typeof PianiCucinaBagnoRoute
  '/rivestimenti': typeof RivestimentiRoute
  '/scale-complementi': typeof ScaleComplementiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arte-funeraria'
    | '/piani-cucina-bagno'
    | '/rivestimenti'
    | '/scale-complementi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arte-funeraria'
    | '/piani-cucina-bagno'
    | '/rivestimenti'
    | '/scale-complementi'
  id:
    | '__root__'
    | '/'
    | '/arte-funeraria'
    | '/piani-cucina-bagno'
    | '/rivestimenti'
    | '/scale-complementi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArteFunerariaRoute: typeof ArteFunerariaRoute
  PianiCucinaBagnoRoute: typeof PianiCucinaBagnoRoute
  RivestimentiRoute: typeof RivestimentiRoute
  ScaleComplementiRoute: typeof ScaleComplementiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scale-complementi': {
      id: '/scale-complementi'
      path: '/scale-complementi'
      fullPath: '/scale-complementi'
      preLoaderRoute: typeof ScaleComplementiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rivestimenti': {
      id: '/rivestimenti'
      path: '/rivestimenti'
      fullPath: '/rivestimenti'
      preLoaderRoute: typeof RivestimentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piani-cucina-bagno': {
      id: '/piani-cucina-bagno'
      path: '/piani-cucina-bagno'
      fullPath: '/piani-cucina-bagno'
      preLoaderRoute: typeof PianiCucinaBagnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arte-funeraria': {
      id: '/arte-funeraria'
      path: '/arte-funeraria'
      fullPath: '/arte-funeraria'
      preLoaderRoute: typeof ArteFunerariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArteFunerariaRoute: ArteFunerariaRoute,
  PianiCucinaBagnoRoute: PianiCucinaBagnoRoute,
  RivestimentiRoute: RivestimentiRoute,
  ScaleComplementiRoute: ScaleComplementiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
